[package]
name = "adventofcode"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "day11"
path = "src/day1/day1-1.rs"

[[bin]]
name = "day12"
path = "src/day1/day1-2.rs"

[[bin]]
name = "day21"
path = "src/day2/day2-1.rs"

[[bin]]
name = "day22"
path = "src/day2/day2-2.rs"
